# Exercicio de Sala

In [403]:
import pandas as pd
import numpy as np

df = pd.read_csv('BRASILIA_2023.csv', delimiter=';', skiprows=8, encoding='latin1')

In [362]:
df.head()#exibe as primeiras 5 linhas do dataframe

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,0,"887,7","887,7","887,2",NaN,"20,1","17,9","20,9",20,"19,2","17,8",91.0,87.0,87.0,187.0,"3,3","1,2",NaN
1,2023/01/01,0100 UTC,0,"888,1","888,1","887,7",NaN,"19,2","17,5","20,1","19,2","17,8","17,4",90.0,87.0,90.0,153.0,"2,9",",8",NaN
2,2023/01/01,0200 UTC,0,"887,8","888,1","887,8",NaN,"19,3","17,6","19,5",19,"17,8","17,3",90.0,89.0,90.0,145.0,"2,5","1,5",NaN
3,2023/01/01,0300 UTC,0,"887,8","887,9","887,7",NaN,"19,3","17,7","19,4","19,1","17,8","17,5",91.0,90.0,91.0,162.0,"3,2","1,4",NaN
4,2023/01/01,0400 UTC,0,"887,6","887,9","887,6",NaN,"19,7","18,1","19,7","19,1","18,1","17,4",91.0,90.0,90.0,140.0,"5,7","2,7",NaN

In [363]:
df.head(20)#exibe as primeiras 20 linhas do dataframe

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,0,"887,7","887,7","887,2",NaN,"20,1","17,9","20,9",20,"19,2","17,8",91.0,87.0,87.0,187.0,"3,3","1,2",NaN
1,2023/01/01,0100 UTC,0,"888,1","888,1","887,7",NaN,"19,2","17,5","20,1","19,2","17,8","17,4",90.0,87.0,90.0,153.0,"2,9",",8",NaN
2,2023/01/01,0200 UTC,0,"887,8","888,1","887,8",NaN,"19,3","17,6","19,5",19,"17,8","17,3",90.0,89.0,90.0,145.0,"2,5","1,5",NaN
3,2023/01/01,0300 UTC,0,"887,8","887,9","887,7",NaN,"19,3","17,7","19,4","19,1","17,8","17,5",91.0,90.0,91.0,162.0,"3,2","1,4",NaN
4,2023/01/01,0400 UTC,0,"887,6","887,9","887,6",NaN,"19,7","18,1","19,7","19,1","18,1","17,4",91.0,90.0,90.0,140.0,"5,7","2,7",NaN
5,2023/01/01,0500 UTC,0,"886,7","887,6","886,7",NaN,"19,1","17,7","19,7","19,1","18,1","17,7",92.0,90.0,92.0,128.0,"7,1",2,NaN
6,2023/01/01,0600 UTC,0,"886,3","886,8","886,3",NaN,"18,5","17,1","19,1","18,4","17,7","17,1",92.0,92.0,92.0,196.0,4,",4",NaN
7,2023/01/01,0700 UTC,0,"886,4","886,5","886,3",NaN,"18,5","17,3","18,6","18,4","17,4","17,1",93.0,92.0,93.0,98.0,"2,5",",8",NaN
8,2023/01/01,0800 UTC,0,"886,5","886,6","886,4",NaN,"18,2","16,9","18,7","18,2","17,3","16,8",93.0,91.0,92.0,51.0,"3,4",",8",NaN
9,2023/01/01,0900 UTC,0,"887,1","887,1","886,5","2,5","18,1","16,9","18,3",18,17,"16,8",93.0,92.0,93.0,121.0,"3,5","1,6",NaN
10,2023/01/01,1000 UTC,0,"887,9","887,9","887,1","253,8",19,"17,6",19,18,"17,6","16,8",93.0,91.0,91.0,92.0,"3,8",2,NaN
11,2023/01/01,1100 UTC,",2","888,4","888,4","887,9","510,4","19,4","17,5","19,6",19,"17,8","17,4",91.0,89.0,89.0,81.0,"4,7","2,3",NaN
12,2023/01/01,1200 UTC,0,"888,6","888,6","888,4",1483,21,18,21,"19,3","18,4","17,5",90.0,83.0,83.0,56.0,"5,5",3,NaN
13,2023/01/01,1300 UTC,0,"888,7","888,8","888,6","2165,4","22,5","17,9","22,9",21,"19,2","17,8",84.0,74.0,76.0,89.0,6,"3,3",NaN
14,2023/01/01,1400 UTC,0,"888,3","888,7","888,3","3168,9","23,6","18,6","23,8","22,4","19,3","17,6",78.0,71.0,73.0,79.0,"6,2",3,NaN
15,2023/01/01,1500 UTC,0,"887,8","888,4","887,7","3915,1","25,3","17,1","25,5","23,5","19,2","16,7",74.0,60.0,60.0,66.0,"8,1","3,4",NaN
16,2023/01/01,1600 UTC,0,"887,1","887,8","887,1","3856,4","26,4","16,7","26,7","25,1","18,2",16,63.0,53.0,55.0,52.0,"8,1","2,1",NaN
17,2023/01/01,1700 UTC,0,"886,1","887,1","886,1","3338,7","26,3","15,9","27,6",26,"17,4","15,7",57.0,51.0,53.0,71.0,"6,2","2,5",NaN
18,2023/01/01,1800 UTC,0,"885,3","886,1","885,3",2391,"26,9","16,9","27,8","25,8","18,1","15,8",58.0,51.0,54.0,43.0,"5,8",3,NaN
19,2023/01/01,1900 UTC,0,"884,8","885,3","884,8",1542,"25,9","16,5","27,6","25,8","17,5","15,5",57.0,50.0,56.0,73.0,"6,3",3,NaN

In [364]:
df.tail()#exibe as ultimos 5 linhas do dataframe = eu sei qnts linhas tem 8760 (do 0 ao 8759)

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
8755,2023/12/31,1900 UTC,0,"884,2","885,2","884,2","1252,2","26,1","18,4","28,1",26,19,"16,9",64.0,52.0,63.0,1.0,"5,3","2,1",NaN
8756,2023/12/31,2000 UTC,0,"883,7","884,3","883,7","1178,8","27,7","18,1","27,7","25,8","18,2","16,9",62.0,53.0,56.0,314.0,"5,2","1,9",NaN
8757,2023/12/31,2100 UTC,0,"883,5","883,7","883,4",873,"25,5","17,4","27,7","25,5",18,"16,9",62.0,52.0,61.0,300.0,"5,1","2,7",NaN
8758,2023/12/31,2200 UTC,0,"884,5","884,5","883,5",104,"23,4","18,2","25,5","23,4","18,2","17,4",72.0,61.0,72.0,293.0,"4,8",2,NaN
8759,2023/12/31,2300 UTC,0,"885,3","885,3","884,5",NaN,"22,6","18,6","23,4","22,3","18,6","18,3",79.0,73.0,78.0,285.0,"3,7","1,4",NaN

In [365]:
df.tail(10) #exibe as ultimas 10 linhas do dataframe

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
8750,2023/12/31,1400 UTC,0,"887,8","888,1","887,8","3377,9","25,3","17,9","25,3","22,7","19,4","17,4",80.0,62.0,63.0,300.0,"5,1","2,6",NaN
8751,2023/12/31,1500 UTC,0,"887,7","887,8","887,7","2986,7","25,5","18,2","26,1","25,1","19,6","17,6",70.0,62.0,64.0,313.0,"5,9","2,6",NaN
8752,2023/12/31,1600 UTC,0,"887,1","887,7","887,1","2483,1",26,"18,9","26,6","25,4","20,1","17,5",68.0,60.0,65.0,312.0,6,"2,6",NaN
8753,2023/12/31,1700 UTC,0,886,"887,1",886,"3002,1","25,8","18,7","27,4","25,8","20,2","18,6",67.0,61.0,65.0,320.0,"7,1","2,1",NaN
8754,2023/12/31,1800 UTC,0,"885,2","885,9","885,2","1570,1","27,3","17,8","27,4","25,8","19,3","16,4",66.0,53.0,56.0,3.0,"4,5",2,NaN
8755,2023/12/31,1900 UTC,0,"884,2","885,2","884,2","1252,2","26,1","18,4","28,1",26,19,"16,9",64.0,52.0,63.0,1.0,"5,3","2,1",NaN
8756,2023/12/31,2000 UTC,0,"883,7","884,3","883,7","1178,8","27,7","18,1","27,7","25,8","18,2","16,9",62.0,53.0,56.0,314.0,"5,2","1,9",NaN
8757,2023/12/31,2100 UTC,0,"883,5","883,7","883,4",873,"25,5","17,4","27,7","25,5",18,"16,9",62.0,52.0,61.0,300.0,"5,1","2,7",NaN
8758,2023/12/31,2200 UTC,0,"884,5","884,5","883,5",104,"23,4","18,2","25,5","23,4","18,2","17,4",72.0,61.0,72.0,293.0,"4,8",2,NaN
8759,2023/12/31,2300 UTC,0,"885,3","885,3","884,5",NaN,"22,6","18,6","23,4","22,3","18,6","18,3",79.0,73.0,78.0,285.0,"3,7","1,4",NaN

In [366]:
df.shape #Exibe a qtd de linhas e colunas do DataFrame no formato de tupla '(linhas, colunas)'.
# o arquivo tem 8760 linhas e 20 colunas
# shape é um atributo e nao é um metodo que precisa de ()

(8760, 20)

In [367]:
#Gera estatísticas para colunas numéricas, como contagem, média, desvio padrão, vaores min./max. e quartis
df.describe()

,UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))",Unnamed: 19
count,8747.000000,8747.000000,8755.000000,8748.000000,0.0
mean,68.326741,61.435692,64.857910,150.510974,NaN
std,19.268845,19.837790,19.702607,94.346841,NaN
min,19.000000,16.000000,17.000000,1.000000,NaN
25%,54.000000,46.000000,49.000000,87.000000,NaN
50%,70.000000,61.000000,66.000000,119.000000,NaN
75%,86.000000,79.000000,83.000000,200.000000,NaN
max,98.000000,98.000000,98.000000,360.000000,NaN

In [368]:
df.dtypes #retorna os tipos de dados

Data                                                      object
Hora UTC                                                  object
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                          object
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)     object
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)           object
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)          object
RADIACAO GLOBAL (Kj/m²)                                   object
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)              object
TEMPERATURA DO PONTO DE ORVALHO (°C)                      object
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)                object
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)                object
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)          object
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)          object
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                 float64
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                 float64
UMIDADE RELATIVA DO AR, HORARIA (%)                      float64
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                     float64
VENTO, RAJADA MAXIMA (m/s)                                object
VENTO, VELOCIDADE HORARIA (m/s)                           object
Unnamed: 19                                              float64
dtype: object

In [369]:
df.sample() #seleciona uma amotra aleatória de linhas do DataFrame

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
5654,2023/08/24,1400 UTC,0,"887,2","887,7","887,2","2173,5",29,"10,3","30,2","27,7","13,3","10,1",40.0,30.0,31.0,249.0,"5,2","2,1",NaN

In [370]:
df.sample(n=5) #pega 5 linhas aleatoriamente

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
7017,2023/10/20,0900 UTC,0,"887,4","887,4","886,6","4,5","23,1","12,9","24,1","23,1","12,9","12,3",53.0,48.0,53.0,129.0,"5,4","2,4",NaN
1103,2023/02/15,2300 UTC,0,"883,5","883,5","882,9",NaN,"25,9","14,5","26,9","25,9","15,7","14,1",52.0,45.0,49.0,272.0,"3,9","1,7",NaN
4893,2023/07/23,2100 UTC,0,"892,9","892,9","892,5","280,1","22,3","7,4","23,7","22,3","7,9","6,5",38.0,34.0,38.0,64.0,"7,5","2,9",NaN
8158,2023/12/06,2200 UTC,0,886,"886,1","885,7","21,6","24,2",17,26,"23,9","17,2","16,7",66.0,57.0,64.0,131.0,"4,4","1,6",NaN
8151,2023/12/06,1500 UTC,0,"888,2","888,6","888,2","3039,3","26,4","18,9","27,4","26,1","19,6","17,7",64.0,58.0,63.0,123.0,"8,5","3,7",NaN

In [371]:
df.reset_index()  #reseta o indice do DataFrame, útil após filtragens ou amostragens

,index,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),...,TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,0,2023/01/01,0000 UTC,0,"887,7","887,7","887,2",NaN,"20,1","17,9",...,20,"19,2","17,8",91.0,87.0,87.0,187.0,"3,3","1,2",NaN
1,1,2023/01/01,0100 UTC,0,"888,1","888,1","887,7",NaN,"19,2","17,5",...,"19,2","17,8","17,4",90.0,87.0,90.0,153.0,"2,9",",8",NaN
2,2,2023/01/01,0200 UTC,0,"887,8","888,1","887,8",NaN,"19,3","17,6",...,19,"17,8","17,3",90.0,89.0,90.0,145.0,"2,5","1,5",NaN
3,3,2023/01/01,0300 UTC,0,"887,8","887,9","887,7",NaN,"19,3","17,7",...,"19,1","17,8","17,5",91.0,90.0,91.0,162.0,"3,2","1,4",NaN
4,4,2023/01/01,0400 UTC,0,"887,6","887,9","887,6",NaN,"19,7","18,1",...,"19,1","18,1","17,4",91.0,90.0,90.0,140.0,"5,7","2,7",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,8755,2023/12/31,1900 UTC,0,"884,2","885,2","884,2","1252,2","26,1","18,4",...,26,19,"16,9",64.0,52.0,63.0,1.0,"5,3","2,1",NaN
8756,8756,2023/12/31,2000 UTC,0,"883,7","884,3","883,7","1178,8","27,7","18,1",...,"25,8","18,2","16,9",62.0,53.0,56.0,314.0,"5,2","1,9",NaN
8757,8757,2023/12/31,2100 UTC,0,"883,5","883,7","883,4",873,"25,5","17,4",...,"25,5",18,"16,9",62.0,52.0,61.0,300.0,"5,1","2,7",NaN
8758,8758,2023/12/31,2200 UTC,0,"884,5","884,5","883,5",104,"23,4","18,2",...,"23,4","18,2","17,4",72.0,61.0,72.0,293.0,"4,8",2,NaN
8759,8759,2023/12/31,2300 UTC,0,"885,3","885,3","884,5",NaN,"22,6","18,6",...,"22,3","18,6","18,3",79.0,73.0,78.0,285.0,"3,7","1,4",NaN

In [372]:
df_reduzido = df[['Data', 'Hora UTC', 'PRECIPITAÇÃO TOTAL, HORÁRIO (mm)','TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)']]
#Seleciona colunas específicas

In [373]:
df_reduzido.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)",TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
0,2023/01/01,0000 UTC,0,20
1,2023/01/01,0100 UTC,0,"19,2"
2,2023/01/01,0200 UTC,0,19
3,2023/01/01,0300 UTC,0,"19,1"
4,2023/01/01,0400 UTC,0,"19,1"

In [374]:
df_reduzido = df_reduzido.sample(n=1000, random_state=42)

In [375]:
df_reduzido

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)",TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
6056,2023/09/10,0800 UTC,0,"19,6"
5556,2023/08/20,1200 UTC,0,"19,8"
5990,2023/09/07,1400 UTC,0,"21,3"
7674,2023/11/16,1800 UTC,0,"32,5"
3319,2023/05/19,0700 UTC,0,"13,1"
...,...,...,...,...
1071,2023/02/14,1500 UTC,0,"26,9"
2968,2023/05/04,1600 UTC,0,"24,7"
2436,2023/04/12,1200 UTC,0,"20,2"
6143,2023/09/13,2300 UTC,0,"25,9"
5121,2023/08/02,0900 UTC,0,"15,9"

In [376]:
df_reduzido.columns = ['NovoNome1', 'NovoNome2', 'NovoNome3', 'NovoNome4']

In [377]:
df_reduzido

       NovoNome1 NovoNome2 NovoNome3 NovoNome4
6056  2023/09/10  0800 UTC         0      19,6
5556  2023/08/20  1200 UTC         0      19,8
5990  2023/09/07  1400 UTC         0      21,3
7674  2023/11/16  1800 UTC         0      32,5
3319  2023/05/19  0700 UTC         0      13,1
...          ...       ...       ...       ...
1071  2023/02/14  1500 UTC         0      26,9
2968  2023/05/04  1600 UTC         0      24,7
2436  2023/04/12  1200 UTC         0      20,2
6143  2023/09/13  2300 UTC         0      25,9
5121  2023/08/02  0900 UTC         0      15,9

[1000 rows x 4 columns]

In [378]:
coluna1 = df_reduzido['NovoNome1'] #seleciona a coluna 'NovoNome1'
coluna_data = df['Data']

In [379]:
coluna1

6056    2023/09/10
5556    2023/08/20
5990    2023/09/07
7674    2023/11/16
3319    2023/05/19
           ...
1071    2023/02/14
2968    2023/05/04
2436    2023/04/12
6143    2023/09/13
5121    2023/08/02
Name: NovoNome1, Length: 1000, dtype: object

In [380]:
coluna_data

0       2023/01/01
1       2023/01/01
2       2023/01/01
3       2023/01/01
4       2023/01/01
           ...
8755    2023/12/31
8756    2023/12/31
8757    2023/12/31
8758    2023/12/31
8759    2023/12/31
Name: Data, Length: 8760, dtype: object

In [381]:
minimo = df_reduzido['NovoNome1'].min()
minimo

'2023/01/01'

In [382]:
coluna_umidade_relativa = df['UMIDADE RELATIVA DO AR, HORARIA (%)']

In [383]:
coluna_umidade_relativa.dtype #é um metodo por isso nao precisa do ()

dtype('float64')

In [384]:
coluna_umidade_relativa

0       87.0
1       90.0
2       90.0
3       91.0
4       90.0
        ...
8755    63.0
8756    56.0
8757    61.0
8758    72.0
8759    78.0
Name: UMIDADE RELATIVA DO AR, HORARIA (%), Length: 8760, dtype: float64

In [385]:
coluna_umidade_relativa.min()

np.float64(17.0)

In [386]:
coluna_umidade_relativa.max()

np.float64(98.0)

In [387]:
coluna_umidade_relativa.head()

0    87.0
1    90.0
2    90.0
3    91.0
4    90.0
Name: UMIDADE RELATIVA DO AR, HORARIA (%), dtype: float64

In [388]:
round(coluna_umidade_relativa.sum(),2)#soma todas as linhas

np.float64(567831.0)

In [389]:
round(coluna_umidade_relativa.mean(),2) #media contendo todas as linhas

np.float64(64.86)

In [390]:
round(coluna_umidade_relativa.median(),2) #mediana contendo todas as linhas

np.float64(66.0)

In [391]:
round(coluna_umidade_relativa.mode(),2) #moda contendo todas as linhas

0    90.0
Name: UMIDADE RELATIVA DO AR, HORARIA (%), dtype: float64

In [392]:
round(coluna_umidade_relativa.std(),2) #moda contendo todas as linhas

np.float64(19.7)

In [393]:
#Series = compostas por chave(index) e valor 
#São arrays unidimensionais rotulados/nomeados, capazes de armazenar dados de qualquer tipo

#Dataframes = estrutura de dados fundamental em Pandas.
#É uma estrutura bidimensional com linhas e colunas nomeadas, similar a uma tabela.
#Dataframes possuem dois índices (um para linha e um para colunas) ecada linha e coluna individual também é uma Série

In [394]:
coluna_temperatura_maxima = pd.to_numeric(df['PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)'], errors='coerce')

In [395]:
coluna_temperatura_maxima.dtype

dtype('float64')

In [396]:
print(round(coluna_temperatura_maxima.sum(),2))
print(round(coluna_temperatura_maxima.max(),2))
print(round(coluna_temperatura_maxima.min(),2))
print(round(coluna_temperatura_maxima.mean(),2))

775178.0
895.0
882.0
887.95

In [397]:
nulos = df.isnull()
print(nulos) #mostra os nulos do DataFrame

       Data  Hora UTC  PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \
0     False     False                             False
1     False     False                             False
2     False     False                             False
3     False     False                             False
4     False     False                             False
...     ...       ...                               ...
8755  False     False                             False
8756  False     False                             False
8757  False     False                             False
8758  False     False                             False
8759  False     False                             False

      PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  \
0                                                 False
1                                                 False
2                                                 False
3                                                 False
4                                                 False
...                                                 ...
8755                                              False
8756                                              False
8757                                              False
8758                                              False
8759                                              False

      PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)  \
0                                               False
1                                               False
2                                               False
3                                               False
4                                               False
...                                               ...
8755                                            False
8756                                            False
8757                                            False
8758                                            False
8759                                            False

      PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)  \
0                                                False
1                                                False
2                                                False
3                                                False
4                                                False
...                                                ...
8755                                             False
8756                                             False
8757                                             False
8758                                             False
8759                                             False

      RADIACAO GLOBAL (Kj/m²)  TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)  \
0                        True                                         False
1                        True                                         False
2                        True                                         False
3                        True                                         False
4                        True                                         False
...                       ...                                           ...
8755                    False                                         False
8756                    False                                         False
8757                    False                                         False
8758                    False                                         False
8759                     True                                         False

      TEMPERATURA DO PONTO DE ORVALHO (°C)  \
0                                    False
1                                    False
2                                    False
3                                    False
4                                    False
...                                    ...
8755                                 False
8756                                 False
8757                                 False
8758                                 False
8759                                 False

      TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)  \
0                                          False
1                                          False
2                                          False
3                                          False
4                                          False
...                                          ...
8755                                       False
8756                                       False
8757                                       False
8758                                       False
8759                                       False

      TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)  \
0                                          False
1                                          False
2                                          False
3                                          False
4                                          False
...                                          ...
8755                                       False
8756                                       False
8757                                       False
8758                                       False
8759                                       False

      TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)  \
0                                                False
1                                                False
2                                                False
3                                                False
4                                                False
...                                                ...
8755                                             False
8756                                             False
8757                                             False
8758                                             False
8759                                             False

      TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)  \
0                                                False
1                                                False
2                                                False
3                                                False
4                                                False
...                                                ...
8755                                             False
8756                                             False
8757                                             False
8758                                             False
8759                                             False

      UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)  \
0                                        False
1                                        False
2                                        False
3                                        False
4                                        False
...                                        ...
8755                                     False
8756                                     False
8757                                     False
8758                                     False
8759                                     False

      UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)  \
0                                        False
1                                        False
2                                        False
3                                        False
4                                        False
...                                        ...
8755                                     False
8756                                     False
8757                                     False
8758                                     False
8759                                     False

      UMIDADE RELATIVA DO AR, HORARIA (%)  \
0                                   False
1                                   False
2                                   False
3                                   False
4                                   False
...                                   ...
8755                                False
8756                                False
8757                                False
8758                                False
8759                                False

      VENTO, DIREÇÃO HORARIA (gr) (° (gr))  VENTO, RAJADA MAXIMA (m/s)  \
0                                    False                       False
1                                    False                       False
2                                    False                       False
3                                    False                       False
4                                    False                       False
...                                    ...                         ...
8755                                 False                       False
8756                                 False                       False
8757                                 False                       False
8758                                 False                       False
8759                                 False                       False

      VENTO, VELOCIDADE HORARIA (m/s)  Unnamed: 19
0                               False         True
1                               False         True
2                               False         True
3                               False         True
4                               False         True
...                               ...          ...
8755                            False         True
8756                            False         True
8757                            False         True
8758                            False         True
8759                            False         True

[8760 rows x 20 columns]

In [398]:
df.isnull().sum() #mostra a quantidade de nulos por coluna

Data                                                        0
Hora UTC                                                    0
PRECIPITAÇÃO TOTAL, HORÁRIO (mm)                            5
PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)       5
PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)            13
PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)           13
RADIACAO GLOBAL (Kj/m²)                                  4087
TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)                5
TEMPERATURA DO PONTO DE ORVALHO (°C)                        5
TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)                 13
TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)                 13
TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)           13
TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)           13
UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)                   13
UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)                   13
UMIDADE RELATIVA DO AR, HORARIA (%)                         5
VENTO, DIREÇÃO HORARIA (gr) (° (gr))                       12
VENTO, RAJADA MAXIMA (m/s)                                 13
VENTO, VELOCIDADE HORARIA (m/s)                            10
Unnamed: 19                                              8760
dtype: int64

In [399]:
df_sem_nulos = df.dropna(axis=0, how='any') #remove linhas com qualquer valores nulos
df_sem_nulos

Empty DataFrame
Columns: [Data, Hora UTC, PRECIPITAÇÃO TOTAL, HORÁRIO (mm), PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB), PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB), PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB), RADIACAO GLOBAL (Kj/m²), TEMPERATURA DO AR - BULBO SECO, HORARIA (°C), TEMPERATURA DO PONTO DE ORVALHO (°C), TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C), TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C), TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C), TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C), UMIDADE REL. MAX. NA HORA ANT. (AUT) (%), UMIDADE REL. MIN. NA HORA ANT. (AUT) (%), UMIDADE RELATIVA DO AR, HORARIA (%), VENTO, DIREÇÃO HORARIA (gr) (° (gr)), VENTO, RAJADA MAXIMA (m/s), VENTO, VELOCIDADE HORARIA (m/s), Unnamed: 19]
Index: []

In [412]:
df_drop_all = df.dropna(axis=0, how='all') #só remove se todos os valores da linha forem ausentes
df_drop_all

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,0,"887,7","887,7","887,2",NaN,"20,1","17,9","20,9",20,"19,2","17,8",91.0,87.0,87.0,187.0,"3,3","1,2",NaN
1,2023/01/01,0100 UTC,0,"888,1","888,1","887,7",NaN,"19,2","17,5","20,1","19,2","17,8","17,4",90.0,87.0,90.0,153.0,"2,9",",8",NaN
2,2023/01/01,0200 UTC,0,"887,8","888,1","887,8",NaN,"19,3","17,6","19,5",19,"17,8","17,3",90.0,89.0,90.0,145.0,"2,5","1,5",NaN
3,2023/01/01,0300 UTC,0,"887,8","887,9","887,7",NaN,"19,3","17,7","19,4","19,1","17,8","17,5",91.0,90.0,91.0,162.0,"3,2","1,4",NaN
4,2023/01/01,0400 UTC,0,"887,6","887,9","887,6",NaN,"19,7","18,1","19,7","19,1","18,1","17,4",91.0,90.0,90.0,140.0,"5,7","2,7",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2023/12/31,1900 UTC,0,"884,2","885,2","884,2","1252,2","26,1","18,4","28,1",26,19,"16,9",64.0,52.0,63.0,1.0,"5,3","2,1",NaN
8756,2023/12/31,2000 UTC,0,"883,7","884,3","883,7","1178,8","27,7","18,1","27,7","25,8","18,2","16,9",62.0,53.0,56.0,314.0,"5,2","1,9",NaN
8757,2023/12/31,2100 UTC,0,"883,5","883,7","883,4",873,"25,5","17,4","27,7","25,5",18,"16,9",62.0,52.0,61.0,300.0,"5,1","2,7",NaN
8758,2023/12/31,2200 UTC,0,"884,5","884,5","883,5",104,"23,4","18,2","25,5","23,4","18,2","17,4",72.0,61.0,72.0,293.0,"4,8",2,NaN
8759,2023/12/31,2300 UTC,0,"885,3","885,3","884,5",NaN,"22,6","18,6","23,4","22,3","18,6","18,3",79.0,73.0,78.0,285.0,"3,7","1,4",NaN

In [400]:
df_sem_nulos_colunas = (df.dropna(axis=1))
df_sem_nulos_colunas #remove colunas que contenham valores nulos

            Data  Hora UTC
0     2023/01/01  0000 UTC
1     2023/01/01  0100 UTC
2     2023/01/01  0200 UTC
3     2023/01/01  0300 UTC
4     2023/01/01  0400 UTC
...          ...       ...
8755  2023/12/31  1900 UTC
8756  2023/12/31  2000 UTC
8757  2023/12/31  2100 UTC
8758  2023/12/31  2200 UTC
8759  2023/12/31  2300 UTC

[8760 rows x 2 columns]

In [401]:
df_preenchido = df.fillna(0)
df_preenchido

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,0,"887,7","887,7","887,2",0,"20,1","17,9","20,9",20,"19,2","17,8",91.0,87.0,87.0,187.0,"3,3","1,2",0.0
1,2023/01/01,0100 UTC,0,"888,1","888,1","887,7",0,"19,2","17,5","20,1","19,2","17,8","17,4",90.0,87.0,90.0,153.0,"2,9",",8",0.0
2,2023/01/01,0200 UTC,0,"887,8","888,1","887,8",0,"19,3","17,6","19,5",19,"17,8","17,3",90.0,89.0,90.0,145.0,"2,5","1,5",0.0
3,2023/01/01,0300 UTC,0,"887,8","887,9","887,7",0,"19,3","17,7","19,4","19,1","17,8","17,5",91.0,90.0,91.0,162.0,"3,2","1,4",0.0
4,2023/01/01,0400 UTC,0,"887,6","887,9","887,6",0,"19,7","18,1","19,7","19,1","18,1","17,4",91.0,90.0,90.0,140.0,"5,7","2,7",0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2023/12/31,1900 UTC,0,"884,2","885,2","884,2","1252,2","26,1","18,4","28,1",26,19,"16,9",64.0,52.0,63.0,1.0,"5,3","2,1",0.0
8756,2023/12/31,2000 UTC,0,"883,7","884,3","883,7","1178,8","27,7","18,1","27,7","25,8","18,2","16,9",62.0,53.0,56.0,314.0,"5,2","1,9",0.0
8757,2023/12/31,2100 UTC,0,"883,5","883,7","883,4",873,"25,5","17,4","27,7","25,5",18,"16,9",62.0,52.0,61.0,300.0,"5,1","2,7",0.0
8758,2023/12/31,2200 UTC,0,"884,5","884,5","883,5",104,"23,4","18,2","25,5","23,4","18,2","17,4",72.0,61.0,72.0,293.0,"4,8",2,0.0
8759,2023/12/31,2300 UTC,0,"885,3","885,3","884,5",0,"22,6","18,6","23,4","22,3","18,6","18,3",79.0,73.0,78.0,285.0,"3,7","1,4",0.0

In [413]:
df_substituido = df.replace('0', np.nan) #Substitui todos os valores 0 por NaN (pode ser outros valores tambem)
df_substituido #para substituir, o 0 tem que ser passado como uma string pq é como ele está no arquivo

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,NaN,"887,7","887,7","887,2",NaN,"20,1","17,9","20,9",20,"19,2","17,8",91.0,87.0,87.0,187.0,"3,3","1,2",NaN
1,2023/01/01,0100 UTC,NaN,"888,1","888,1","887,7",NaN,"19,2","17,5","20,1","19,2","17,8","17,4",90.0,87.0,90.0,153.0,"2,9",",8",NaN
2,2023/01/01,0200 UTC,NaN,"887,8","888,1","887,8",NaN,"19,3","17,6","19,5",19,"17,8","17,3",90.0,89.0,90.0,145.0,"2,5","1,5",NaN
3,2023/01/01,0300 UTC,NaN,"887,8","887,9","887,7",NaN,"19,3","17,7","19,4","19,1","17,8","17,5",91.0,90.0,91.0,162.0,"3,2","1,4",NaN
4,2023/01/01,0400 UTC,NaN,"887,6","887,9","887,6",NaN,"19,7","18,1","19,7","19,1","18,1","17,4",91.0,90.0,90.0,140.0,"5,7","2,7",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2023/12/31,1900 UTC,NaN,"884,2","885,2","884,2","1252,2","26,1","18,4","28,1",26,19,"16,9",64.0,52.0,63.0,1.0,"5,3","2,1",NaN
8756,2023/12/31,2000 UTC,NaN,"883,7","884,3","883,7","1178,8","27,7","18,1","27,7","25,8","18,2","16,9",62.0,53.0,56.0,314.0,"5,2","1,9",NaN
8757,2023/12/31,2100 UTC,NaN,"883,5","883,7","883,4",873,"25,5","17,4","27,7","25,5",18,"16,9",62.0,52.0,61.0,300.0,"5,1","2,7",NaN
8758,2023/12/31,2200 UTC,NaN,"884,5","884,5","883,5",104,"23,4","18,2","25,5","23,4","18,2","17,4",72.0,61.0,72.0,293.0,"4,8",2,NaN
8759,2023/12/31,2300 UTC,NaN,"885,3","885,3","884,5",NaN,"22,6","18,6","23,4","22,3","18,6","18,3",79.0,73.0,78.0,285.0,"3,7","1,4",NaN